{
 "title": "IOT Angers - Supervision",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Alertes Actives",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot-capteurs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesures_brutes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alerte\")\r\n  |> keep(columns: [\"_time\", \"capteur_id\", \"_value\"])\r\n  |> rename(columns: {_time: \"Horodatage\", capteur_id: \"Capteur\", _value: \"Alerte\"})\r\n  |> sort(columns: [\"Horodatage\"], desc: true)"
    }
   ]
  },
  {
   "title": "Trafic routier — Véhicules/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"iot-capteurs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesures_brutes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"capteur_id\"] == \"trafic_01\")"
    }
   ]
  },
  {
   "title": "Remplissage des poubelles (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot-capteurs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesures_brutes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"capteur_id\"] == \"dechet_01\")"
    }
   ]
  },
  {
   "title": "Qualité de l'air — NO₂ (µg/m³)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"iot-capteurs\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mesures_brutes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"capteur_id\"] == \"air_01\")"
    }
   ]
  }
 ]
}